collection_name: agent
persist_directory: choma_db
vector_recall_k: 30
data_path: data
md5_hex_store: md5.txt
allow_knowledge_file_type: ["txt","pdf"]


chunk_size: 100
chunk_overlap: 10
separators: ["\n\n","\n",".","!","?"," ", "？",",","。"]